name: UnitalSZ
version: 0.6
date: 20/03/2020
description: |
    Algorithms and libraries of abstract unitals and their embeddings

authors:
    - name: Gábor Péter Nagy
      url: http://www.math.u-szeged.hu/~nagyg
    - name: Dávid Mezőfi
      url: http://www.math.u-szeged.hu/~mezofi

maintainers:
    - name: Gábor Péter Nagy
      url: http://www.math.u-szeged.hu/~nagyg
    - name: Dávid Mezőfi
      url: http://www.math.u-szeged.hu/~mezofi

GAP: ">= 4.8"

needed-pkgs:
    - name: "GAPDoc"
      version: ">= 1.6"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"
    - name: "Digraphs"
      version: ">= 0.11"
      url: "https://gap-packages.github.io/Digraphs"
    - name: "io"
      version: ">=4.5"
      url: "https://gap-packages.github.io/io"

www: https://nagygp.github.io/UnitalSZ/
readme: README.md
packageinfo: https://nagygp.github.io/UnitalSZ/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/nagygp/UnitalSZ/releases/download/v0.6/UnitalSZ-0.6.tar.gz

abstract: |
    <p>This is a GAP package containing methods for abstract unitals as block designs.</p> <p>There are methods for automorphisms and isomorphisms and for the embeddings of unitals in the finite Desarguesian projective plane. There are functions for constructing unitals and some libraries of unitals os small order.</p>

status: dev
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
