#
# fullpoints: Full points of unitals
#
# Declarations
#

#! @Chapter Full points and perspectivities
#! @Section Full points of unitals
#! @Section Group of perspectivities
#! @Section Abstract polar triangles and full point regularity



#! @ChapterInfo Full points and perspectivities, Full points of unitals
#! @Arguments u, b1, b2
#! @Returns The list full point of <A>u</A> w.r.t. the blocks <A>b1,b2</A>. The arguments
#!   <A>b1,b2</A> are either blocks of the unital <A>u</A>, or indices of blocks in 
#!   <C>BlocksOfUnital( u )</C>.
#! @Description According to the paper <Cite Key="KSSz2018"/> by Korchmáros, Siciliano and Szőnyi, 
#!   the point $P$ is a **full point** of the unital $U$ w.r.t. the blocks
#!   $b_1,b_2$ if $P$ is not contained in $b_1$ or $b_2$, and,
#!   the projection with center $P$ from $b_1$ to $b_2$ is a
#!   well-defined bijection.
DeclareOperation( "FullPointsOfUnitalsBlocks", [ IsAbstractUnitalDesign, IsPosInt, IsPosInt ] );
#! @ChapterInfo Full points and perspectivities, Full points of unitals
#! @Arguments u
#! @Returns A list of records <C>r</C> containing the fields <C>r.block1, r.block2, r.fullpts</C>,
#!   where <C>r.fullpts</C> is the set of full point of <A>u</A> w.r.t.
#!   the blocks <C>r.block1, r.block2</C>. The returned list contains all possible full points 
#!   of <A>u</A> up to the automorphism group of <A>u</A>.
#!   That is, if $P$ is a full point w.r.t. the blocks $b_1,b_2$, then there is an
#!   automorphism $\alpha$ of $U$ such that $P^\alpha, b_1^\alpha, b_2^\alpha$ are 
#!   in the list. 
DeclareAttribute( "FullPointsOfUnitalRepresentatives", IsAbstractUnitalDesign );
#! @ChapterInfo Full points and perspectivities, Group of perspectivities
#! @Arguments u, b1, b2[, fullpts]
#! @Returns The group generated by perspectivies from block <A>b1</A> to block <A>b2</A>
#!   of the unital <A>u</A>. Notice that the returned group consists of permutations
#!   of <C>[1..Order(u)+1]</C>. A list of full points can be given as 4th argument. 
#!   It is not checked if the elements of <A>fullpts</A> are full points. 
#! @Description Perspectivities between blocks $b_1, b_2$ of an abstract unital $U$
#!   are projections from $b_1$ to $b_2$ from a center $P$. In order the 
#!   perspectivity be well-defined, $P$ must be a full point w.r.t. $b_1, b_2$. 
DeclareOperation( "PerspectivityGroupOfUnitalsBlocks", [ IsAbstractUnitalDesign, IsList, IsList, IsList ] );
#! @ChapterInfo Full points and perspectivities, Abstract polar triangles and full point regularity
#! @Arguments u
#! @Returns A list of lists each having the form <C>[ b1, b2, b3 ]</C>, where
#! <C>b1, b2, b3</C> are three blocks of the unital <A>u</A> forming an abstract
#! polar triangle. The returned list contains all possible abstract polar
#! triangles of <A>u</A> up to the automorphism group of <A>u</A>.  That is, if
#! the blocks $b_1,b_2,b_3$ form an abstract polar triangle, then there is an
#! automorphism $\alpha$ of $U$ such that $b_1^\alpha, b_2^\alpha, b_3^\alpha$ are
#! in the list. 
DeclareAttribute( "AbstractPolarTrianglesOfUnitalRepresentatives", IsAbstractUnitalDesign );
#! @ChapterInfo Full points and perspectivities, Abstract polar triangles and full point regularity
#! @Arguments u, polartriangle
#! @Returns A latin square associated to the abstract polar triangle
#! <A>polartriangle</A> of the unital <A>u</A>.
DeclareOperation( "LatinSquareOfAbstractPolarTriangle", [ IsAbstractUnitalDesign, IsList ] );
#! @ChapterInfo Full points and perspectivities, Abstract polar triangles and full point regularity
#! @Arguments u
#! @Returns The boolean <C>true</C> if the unital <A>u</A> is full point
#! regular, <C>false</C> otherwise.
#! @Description The unital $U$ is said to be full point regular, if for each
#! non-intersecting pair of blocks $b_1, b_2$ the triple $(U, b_1, b_2)$ is full
#! point regular.
DeclareProperty( "IsFullPointRegularUnital", IsAbstractUnitalDesign );
#! @ChapterInfo Full points and perspectivities, Abstract polar triangles and full point regularity
#! @Arguments u
#! @Returns The boolean <C>true</C> if the unital <A>u</A> is strongly full point
#! regular, <C>false</C> otherwise.
#! @Description The unital $U$ is said to be strongly full point regular, if for
#! each non-intersecting pair of blocks $b_1, b_2$ the triple $(U, b_1, b_2)$ is
#! full point regular.
DeclareProperty( "IsStronglyFullPointRegularUnital", IsAbstractUnitalDesign );
